[package]
name = "mqtt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rumqttc = "0.24.0"
tokio = { version = "1.37.0", features = ["full", "rt-multi-thread"] }
csv = "1.3.0"
debug_print = "1.0.0"